services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnectionString=Host=database;Port=5432;Password=${DB_PASSWORD};Persist Security Info=True;Username=${DB_USER};Database=${DB_DATABASE}
      - ConnectionStrings__RedisConnectionString=redis:6379
      - Jwt__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__AccessTokenExpirationInMinutes=${JWT_ACCESS_TOKEN_EXPIRATION}
      - Jwt__RefreshTokenExpirationInDays=${JWT_REFRESH_TOKEN_EXPIRATION}
      - Ai__ApiKey=${AI_API_KEY}
      - Ai__AnswerCount=${AI_ANWER_COUNT}
      - Ai__ExamCount=${AI_EXAM_COUNT}
      - GoogleAuth__ClientId=${GOOGLE_AUTH_CLIENT_ID}
      - GoogleAuth__Secret=${GOOGLE_AUTH_SECRET}
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  database:
    image: postgres:18-alpine
    container_name: prawko_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./.containers/database:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: prawko_redis
    ports:
      - "6379:6379"
    volumes:
      - ./.containers/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always