/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/footer`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examHistory`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examRules`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examSimulation`; params?: Router.UnknownInputParams; } | { pathname: `/utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/utils/translations`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examResult/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/question/examQuestionWithAnswer/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/footer`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/examHistory`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/examRules`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/examSimulation`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/api`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/translations`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/examResult/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/question/examQuestionWithAnswer/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/footer${`?${string}` | `#${string}` | ''}` | `/exam/examHistory${`?${string}` | `#${string}` | ''}` | `/exam/examRules${`?${string}` | `#${string}` | ''}` | `/exam/examSimulation${`?${string}` | `#${string}` | ''}` | `/utils/api${`?${string}` | `#${string}` | ''}` | `/utils/translations${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/footer`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examHistory`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examRules`; params?: Router.UnknownInputParams; } | { pathname: `/exam/examSimulation`; params?: Router.UnknownInputParams; } | { pathname: `/utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/utils/translations`; params?: Router.UnknownInputParams; } | `/exam/examResult/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/question/examQuestionWithAnswer/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/exam/examResult/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/question/examQuestionWithAnswer/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
